version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
build_script:
- ps: >-

    nuget restore CoreLibrary\nanoFramework.CoreLibrary.sln

    msbuild CoreLibrary\nanoFramework.CoreLibrary.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    nuget restore Windows.Devices.Gpio\nanoFramework.Windows.Devices.Gpio.sln

    msbuild Windows.Devices.Gpio\nanoFramework.Windows.Devices.Gpio.sln /p:Configuration=Release  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: '**\bin\Release\*.nupkg'
  name: Nuget Packages
deploy:
- provider: NuGet
  api_key:
    secure: Szcq1/9Opglxx9fR5wvMFK2GQvQXpdzxGaydUAFbbeldZAPWVkx1/lkL3/jWZN+YmwZeiKerJlQpG7GBMNpooe6RUIDyNBDnR81IU8N5+fo=
  skip_symbols: true
